// config.h

#ifndef CONFIG_H
#define CONFIG_H

#define UNICAST_CHANNEL 144
#define BROADCAST_CHANNEL 129
#define TRUCK_ADDR 8
#define BIN_TO_BIN_ALPHA 0.01
#define BIN_TO_TRUCK_ALPHA 0.5
#define MAX_RETRANSMISSIONS 20
#define MAX_GEN_TRASH 10
#define FULL_THRESHOLD 100
#define ALERT_THRESHOLD (FULL_THRESHOLD-15)
#define ND_MIN_INTERVAL 30
#define ND_MAX_INTERVAL 60
#define MAX_NODES 256
#define BUSY_TIMER_DIVIDER 100
#define MAX_COORDINATE 50


#endif // CONFIG_H
